# Generated by Django 2.2 on 2019-04-24 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveIntegerField()),
                ('movie_id', models.PositiveIntegerField()),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('popularity', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('original_language', models.CharField(blank=True, max_length=5)),
                ('adult', models.BooleanField(default=False, help_text='check box if movie is for adults only')),
                ('overview', models.TextField(blank=True, max_length=500)),
                ('release_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
