# Generated by Django 2.2 on 2019-04-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveIntegerField()),
                ('movie_id', models.PositiveIntegerField()),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=2)),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
    ]
