# Generated by Django 2.2 on 2019-04-23 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieblock',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movieblock',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='movieblock',
            name='original_language',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='movieblock',
            name='overview',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='movieblock',
            name='popularity',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=7),
        ),
        migrations.AddField(
            model_name='movieblock',
            name='poster_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='movieblock',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movieblock',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='movieblock',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
