# Generated by Django 2.2 on 2019-04-25 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieList', '0003_movieblock_genre_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieblock',
            name='genre_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, default=0), blank=True, default=list, size=8),
        ),
    ]
