# Generated by Django 2.2 on 2019-04-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieList', '0003_auto_20190423_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieblock',
            name='popularity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
