# Generated by Django 2.2 on 2019-04-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieList', '0004_auto_20190423_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieblock',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='movieblock',
            name='overview',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='movieblock',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='movieblock',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
